apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: client
  name: client-pods-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tenant
  name: tenant-pods-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: finans
  name: finans-pods-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: databi
  name: databi-pods-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-pods-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-pods-writer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "update", "patch","delete"] 